### ISSUE TITLE
改用其他域名游戏依然会向mhws.io发送请求

### ISSUE THREAD

**Issue by EdLovecraft** [KujouRinka/mhws_beta_server#10]
![image](https://github.com/user-attachments/assets/1295682e-f9ea-49c4-8241-069d12e5c3b0)
![image](https://github.com/user-attachments/assets/f4cd32fd-c05f-4c98-a559-0df0a7fc996b)
![image](https://github.com/user-attachments/assets/b5cb4709-b6ae-41ad-9e95-590f3c975cf7)
![image](https://github.com/user-attachments/assets/cad7b60b-3a90-401e-ab4d-2b71f6c12041)
我想尝试能否不用charles只通过修改hosts文件将hjm.rebe.capcom.com重定向到对应的服务器IP游玩游戏，应该是把所有mhws.io相关的字样都改成了hjm.rebe.capcom.com，但通过charles捕获流量发现游戏仍会对mhws.io发出请求。我也尝试过正常的使用方法，仅仅只是把mhws.io替换成别的域名然后通过charles把hjm.rebe.capcom.com重定向到别的域名，但游戏依然会对mhws.io发出请求

**Comment by KujouRinka** [comment]
`system.json` 中 `custom_property` 字段中的 base64 字段也包含了域名的请求的信息，主要是 wss 的请求 host，也许是这一点。如果您没有修改其中的地址，可能会出现这种情况。解码后字段如下
```json
{
  "obt_info": {
    "env": 1,
    "start_time": 1730428200,
    "end_time": 1735653600
  },
  "qa3": {
    "api": "https://mhws.io",
    "notify": "wss://mhws.io"
  }
}
```
这一段确实和代码中的 `apiHost` 配合得不太好。

**Comment by EdLovecraft** [comment]
> `system.json` 中 `custom_property` 字段中的 base64 字段也包含了域名的请求的信息，主要是 wss 的请求 host，也许是这一点。如果您没有修改其中的地址，可能会出现这种情况。解码后字段如下
> 
> ```json
> {
>   "obt_info": {
>     "env": 1,
>     "start_time": 1730428200,
>     "end_time": 1735653600
>   },
>   "qa3": {
>     "api": "https://mhws.io",
>     "notify": "wss://mhws.io"
>   }
> }
> ```
> 
> 这一段确实和代码中的 `apiHost` 配合得不太好。

感谢解答！问题已解决

**Comment by KujouRinka** [comment]
稍微改了一下，现在应该没问题了。
