### ISSUE TITLE
指定 --api-host 参数的目的是什么呢?

### ISSUE THREAD

**Issue by pangliang** [KujouRinka/mhws_beta_server#14]
我能够理解, 目的是让游戏把 mtm 的请求发到指定服务器上 而不是默认的 mhws.io, 但问题是:
* `/systems/EAR-B-WW/00001/system.json` 最开始的这个接口游戏是写死了访问 `hjm.rebe.capcom.com`的对吧?
* 因此肯定要想办法把 hjm.rebe.capcom.com 请求转发到安装了 server 的机器上, 域名hosts指向也好charles转发也罢
* 既然可以把 hjm.rebe.capcom.com 发到指定服务器, 那同样也把 mhws.io 也发到 server机器上就行
* 对于 server 机器来讲, 可以接受 hjm.rebe.capcom.com 的请求, 肯定也能接受 mhws.io 的请求

也就是说, 怎么处理hjm.rebe.capcom.com就怎么处理mhws.io, hjm.rebe.capcom.com又不能变, 为啥要提供mhws.io可变的能力?

我只是讨论讨论哈, 因为看昨晚的新的修改, 为--api-host做了好多工作, 感觉没必要呢

**Comment by XianYuDaXian** [comment]
![image](https://github.com/user-attachments/assets/f9a3e571-6e46-40c3-bd94-2a8959da6be9)
在这个项目还没出来以前，我想着和beta预载的时候一样，单纯修改system.json就能进去，后来发现还需要一个steam身份认证，域名是mtm.rebe.capcom.com，大概就是为了模拟这个请求？

**Comment by pangliang** [comment]
> ![image](https://private-user-images.githubusercontent.com/20138259/384776839-f9a3e571-6e46-40c3-bd94-2a8959da6be9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTg3NTIsIm5iZiI6MTczMTI5ODQ1MiwicGF0aCI6Ii8yMDEzODI1OS8zODQ3NzY4MzktZjlhM2U1NzEtNmU0Ni00MGMzLWJkOTQtMmE4OTU5ZGE2YmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA0MTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0Mzk1MzQ0NzkwODgwZjEzYjViMWQ4NzRlMDQxYTAxYjRhZTUwYTFiYWJjZTNhM2RkN2ZjZGY1YWJmNjk5NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BxZQZ-yUxMxS6o8JoOB_L4Y0MCPeM7pH6s1i2FGqFko) 在这个项目还没出来以前，我想着和beta预载的时候一样，单纯修改system.json就能进去，后来发现还需要一个steam身份认证，域名是mtm.rebe.capcom.com，大概就是为了模拟这个请求？

哦, 那就是摸索过程中的遗留问题吧? 也就是说, /systems/EAR-B-WW/00001/system.json 原来返回的也不是 mhws.io;
原来是mtm.rebe.capcom.com, 那其实连这个不改也行, mtm.rebe.capcom.com也跟 hjm.rebe.capcom.com同样处理

**Comment by atYuguo** [comment]
也要考虑有些人会真的买域名在公网上搭服务器，如果没有 --api-host 那 http header 会出问题。

**Comment by pangliang** [comment]
> 也要考虑有些人会真的买域名在公网上搭服务器，如果没有 --api-host 那 http header 会出问题。

这个我明白，比如有个公网服务器xxx.com，但是首次访问的接口的hjm.rebe.capcom.com没法修改不是么？需要首先解决hjm.rebe.capcom.com转发xxx.com的问题。

那如果能解决，那同样的办法mhws.io转发xxx.com就可以了

**Comment by KujouRinka** [comment]
> > 也要考虑有些人会真的买域名在公网上搭服务器，如果没有 --api-host 那 http header 会出问题。
> 
> 这个我明白，比如有个公网服务器xxx.com，但是首次访问的接口的hjm.rebe.capcom.com没法修改不是么？需要首先解决hjm.rebe.capcom.com转发xxx.com的问题。
> 
> 那如果能解决，那同样的办法mhws.io转发xxx.com就可以了

是的，如果将使用其他的域名的话必须要搭配 MITM，且若还需要游玩其他卡普空游戏，对 hosts 的反复修改也许挺困惑的，提供这个参数主要是为本地搭建服务器且懒得反复修改 hosts 的人（比如我）一个多的选择。
