### ISSUE TITLE
exit status 1

### ISSUE THREAD

**Issue by CieloSun** [KujouRinka/mhws_beta_server#2]
![image](https://github.com/user-attachments/assets/9bbdc28b-6de9-41cf-86ed-97629fdb998a)
按readme全套弄完启动go程序报这个。

**Comment by KujouRinka** [comment]
参数得是你监听的 IP 地址，不是 Domain 哦

**Comment by CieloSun** [comment]
OKOK，搞定了，感谢感谢。
