### ISSUE TITLE
请求删除数据

### ISSUE THREAD

**Issue by HalcyonAlcedo** [KujouRinka/mhws_beta_server#3]
您好，您的steam_sign_ear-b-ww.json文件中包含了我的steam数据，请删除！
这是我的steam主页https://steamcommunity.com/profiles/76561198053787583/

**Comment by KujouRinka** [comment]
非常抱歉，脱敏的时候疏忽了，现在已经将敏感数据从 log 中去除。
这些数据包的来源是 Youtube 上某博主的分享，还请您注意：https://www.youtube.com/watch?v=JoQLp4Ao5uU
给您造成的困惑真的很抱歉。
