### ISSUE TITLE
您好，请问移除的那个steam_sign_ear-b-ww.json文件有什么作用？

### ISSUE THREAD

**Issue by Zhanghailin1995** [KujouRinka/mhws_beta_server#6]
没有这个文件/steam-steam/sign/EAR-B-WW请求会返回404，这会影响游戏正常运行吗？如果需要这个文件，有没有办法自己构建一个？

**Comment by KujouRinka** [comment]
jwt 签名的数据。会。应该需要逆向，或者 replay。
