### ISSUE TITLE
运行后只请求了一个system.json后就没有下一步动作了

### ISSUE THREAD

**Issue by XianYuDaXian** [KujouRinka/mhws_beta_server#8]
把system.json里mtm的域名指向A 团队的服务器就能正常请求其他文件，请问该如何做？使用的是Proxifier+charles。
![屏幕截图 2024-11-08 195750](https://github.com/user-attachments/assets/c5ef705f-9851-453f-9923-de31d02149e1)

**Comment by KujouRinka** [comment]
经测试 proxifier 对运行在本机的服务兼容性有问题，建议只使用 Charles，如果手上有多余的机器，可以在另外一台机器上跑服务器。

**Comment by azio7** [comment]
我把system.json中的mtm的值替换成原来的域名仍报这个错，但是能进入游戏

**Comment by XianYuDaXian** [comment]
> 我把system.json中的mtm的值替换成原来的域名仍报这个错，但是能进入游戏

但是这样无法读取存档，只能删除存档全新开始，而且打完僻兽就要求集会连接网络，然后就进行不下去了

**Comment by azio7** [comment]
> > 我把system.json中的mtm的值替换成原来的域名仍报这个错，但是能进入游戏
> 
> 但是这样无法读取存档，只能删除存档全新开始，而且打完僻兽就要求集会连接网络，然后就进行不下去了

对，读取不了，但是打完僻兽还能继续玩
我的方法是保存第一章打完青蛙还没进入下一个剧情的存档，没结束任务的存档不需要连集会，但是会强制接打僻兽的任务
我用clash的tun劫持mhws的连接，socks转发给mitmproxy

**Comment by XianYuDaXian** [comment]
> > > 我把system.json中的mtm的值替换成原来的域名仍报这个错，但是能进入游戏
> > 
> > 
> > 但是这样无法读取存档，只能删除存档全新开始，而且打完僻兽就要求集会连接网络，然后就进行不下去了
> 
> 对，读取不了，但是打完僻兽还能继续玩 我的方法是保存第一章打完青蛙还没进入下一个剧情的存档，没结束任务的存档不需要连集会，但是会强制接打僻兽的任务 我用clash的tun劫持mhws的连接，socks转发给mitmproxy

所以我现在直接在局域网另一台主机运行服务，生成包含三个域名的证书，然后游戏机安装证书和修改hosts指向到服务器，现在完美运行
